### Health
GET http://localhost:3000/api/projects

### Archived
GET http://localhost:3000/api/projects?archived=1

### Tag
GET http://localhost:3000/api/projects?tagId={{tagId}}

### Tag + Archived
GET http://localhost:3000/api/projects?tagId={{tagId}}&archived=1

### ====== POST ======
